name_list = [

 'Kobe Bryant',
 'Lebron James',
 'Michael Jordan',
 'James Harden',
 'Stephen Curry',
 'Anthony Davis',
 'Paul George',
 'Russel Westbrook',
 'Chris Paul',
 'Giannis Antetokoumpo',
 'Tim Duncan',
 'Kevin Garnett',
 'Kyle Lowry',
 'Rudy Gorbet',
 'Carmelo Anthony',
 'Joel Embiid',
 'Marc Gasol',
 'Vince Carter',
 'Jimmy Butler',
 'Kemba Walker',
 'Oscar Robertson',
 'Steve Nash', ]